spring:
  application:
    name: "configserver"
  profiles:
    # active: native
    active: git
  cloud:
    config:
      server:
        # native:
          # search-locations: "classpath:/config"
          # search-locations: "file:///Users//ada1//UdemyMicroservicesSpringBoot//section6//v2//config"
        git:
          uri: "https://github.com/CodeCode-123/microservices-section6-v2-spring-cloud-config-yamls.git"
          default-label: main
          timeout: 5
          clone-on-start: true
          force-pull: true
encrypt:
  key: "2b6ea49aa01385a322169bf34373781b266f1546d6fd21b5053cf8f0c9d05fdb"

server:
  port: 8071